# Generated by Django 4.0.5 on 2022-06-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_maker', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('office_address', models.CharField(max_length=100)),
                ('user_doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.people')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=200, verbose_name='')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.people')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Address', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=70)),
                ('user_Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.people')),
            ],
        ),
    ]
