# Generated by Django 4.0.5 on 2022-06-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_people_user_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_Address',
        ),
        migrations.AddField(
            model_name='address',
            name='State',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='Telephone',
            field=models.CharField(default=1, max_length=70),
        ),
    ]
