# Generated by Django 4.0.5 on 2022-06-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_address_user_address_address_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='user_Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.address'),
        ),
    ]
